import React, { useState } from 'react';
import SoulShipOdyssey from './SoulShipOdyssey';

const PortalGames: React.FC = () => {
    const [activeGame, setActiveGame] = useState<string | null>(null);

    const GameLauncher = () => (
        <div className="flex items-center justify-center h-full animate-[fadeIn_0.5s_ease-out]">
            <div className="w-full max-w-sm bg-black/30 rounded-lg border border-cyan-700/50 p-6 text-center shadow-lg shadow-cyan-900/50">
                <h2 className="font-orbitron text-2xl text-white mb-2">Soul Ship Odyssey</h2>
                <p className="text-gray-400 text-sm mb-6">
                    A mini-game where you guide a starship carrying 5000 souls through a procedurally generated space grid. Discover mysterious events and navigate the unknown, with sector descriptions generated by Gemini.
                </p>
                <button
                    onClick={() => setActiveGame('soul-ship-odyssey')}
                    className="w-full font-orbitron bg-cyan-600 hover:bg-cyan-500 text-white font-bold py-3 px-4 rounded-lg shadow-lg shadow-cyan-500/30 transition-all duration-300 transform hover:scale-105"
                >
                    Launch Simulation
                </button>
            </div>
        </div>
    );

    if (activeGame === 'soul-ship-odyssey') {
        return (
            <div className="relative h-[calc(100vh-10rem)] -m-4 sm:-m-6 md:-m-8">
                <SoulShipOdyssey />
                <button
                    onClick={() => setActiveGame(null)}
                    className="absolute top-4 right-4 z-50 font-orbitron bg-red-600/80 hover:bg-red-500/80 text-white text-xs font-bold py-2 px-4 rounded shadow-lg transition-all duration-300"
                >
                    Exit Simulation
                </button>
            </div>
        );
    }
    
    return <GameLauncher />;
};

export default PortalGames;
